/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CorpusRouteImport } from './routes/corpus'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ApiProcessStreamRouteImport } from './routes/api/process-stream'
import { Route as ApiPreprocessImageRouteImport } from './routes/api/preprocess-image'
import { Route as ApiClassifyPageRouteImport } from './routes/api/classify-page'
import { Route as ApiHandoffSessionIdRouteImport } from './routes/api/handoff.$sessionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpusRoute = CorpusRouteImport.update({
  id: '/corpus',
  path: '/corpus',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessStreamRoute = ApiProcessStreamRouteImport.update({
  id: '/api/process-stream',
  path: '/api/process-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreprocessImageRoute = ApiPreprocessImageRouteImport.update({
  id: '/api/preprocess-image',
  path: '/api/preprocess-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClassifyPageRoute = ApiClassifyPageRouteImport.update({
  id: '/api/classify-page',
  path: '/api/classify-page',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHandoffSessionIdRoute = ApiHandoffSessionIdRouteImport.update({
  id: '/api/handoff/$sessionId',
  path: '/api/handoff/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/corpus': typeof CorpusRoute
  '/documents': typeof DocumentsRoute
  '/process': typeof ProcessRoute
  '/settings': typeof SettingsRoute
  '/api/classify-page': typeof ApiClassifyPageRoute
  '/api/preprocess-image': typeof ApiPreprocessImageRoute
  '/api/process-stream': typeof ApiProcessStreamRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/handoff/$sessionId': typeof ApiHandoffSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/corpus': typeof CorpusRoute
  '/documents': typeof DocumentsRoute
  '/process': typeof ProcessRoute
  '/settings': typeof SettingsRoute
  '/api/classify-page': typeof ApiClassifyPageRoute
  '/api/preprocess-image': typeof ApiPreprocessImageRoute
  '/api/process-stream': typeof ApiProcessStreamRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/handoff/$sessionId': typeof ApiHandoffSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/corpus': typeof CorpusRoute
  '/documents': typeof DocumentsRoute
  '/process': typeof ProcessRoute
  '/settings': typeof SettingsRoute
  '/api/classify-page': typeof ApiClassifyPageRoute
  '/api/preprocess-image': typeof ApiPreprocessImageRoute
  '/api/process-stream': typeof ApiProcessStreamRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/handoff/$sessionId': typeof ApiHandoffSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/corpus'
    | '/documents'
    | '/process'
    | '/settings'
    | '/api/classify-page'
    | '/api/preprocess-image'
    | '/api/process-stream'
    | '/projects/$projectId'
    | '/projects/'
    | '/api/handoff/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/corpus'
    | '/documents'
    | '/process'
    | '/settings'
    | '/api/classify-page'
    | '/api/preprocess-image'
    | '/api/process-stream'
    | '/projects/$projectId'
    | '/projects'
    | '/api/handoff/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/corpus'
    | '/documents'
    | '/process'
    | '/settings'
    | '/api/classify-page'
    | '/api/preprocess-image'
    | '/api/process-stream'
    | '/projects/$projectId'
    | '/projects/'
    | '/api/handoff/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CorpusRoute: typeof CorpusRoute
  DocumentsRoute: typeof DocumentsRoute
  ProcessRoute: typeof ProcessRoute
  SettingsRoute: typeof SettingsRoute
  ApiClassifyPageRoute: typeof ApiClassifyPageRoute
  ApiPreprocessImageRoute: typeof ApiPreprocessImageRoute
  ApiProcessStreamRoute: typeof ApiProcessStreamRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiHandoffSessionIdRoute: typeof ApiHandoffSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpus': {
      id: '/corpus'
      path: '/corpus'
      fullPath: '/corpus'
      preLoaderRoute: typeof CorpusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process-stream': {
      id: '/api/process-stream'
      path: '/api/process-stream'
      fullPath: '/api/process-stream'
      preLoaderRoute: typeof ApiProcessStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preprocess-image': {
      id: '/api/preprocess-image'
      path: '/api/preprocess-image'
      fullPath: '/api/preprocess-image'
      preLoaderRoute: typeof ApiPreprocessImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/classify-page': {
      id: '/api/classify-page'
      path: '/api/classify-page'
      fullPath: '/api/classify-page'
      preLoaderRoute: typeof ApiClassifyPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/handoff/$sessionId': {
      id: '/api/handoff/$sessionId'
      path: '/api/handoff/$sessionId'
      fullPath: '/api/handoff/$sessionId'
      preLoaderRoute: typeof ApiHandoffSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CorpusRoute: CorpusRoute,
  DocumentsRoute: DocumentsRoute,
  ProcessRoute: ProcessRoute,
  SettingsRoute: SettingsRoute,
  ApiClassifyPageRoute: ApiClassifyPageRoute,
  ApiPreprocessImageRoute: ApiPreprocessImageRoute,
  ApiProcessStreamRoute: ApiProcessStreamRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiHandoffSessionIdRoute: ApiHandoffSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
